baseURL = "https://dakee0.github.io/"
languageCode = "fr-ch"
title = "Loïc's Space"
theme = ["hugo-embed-pdf-shortcode", "hugo-theme-digital-garden"]
enableInlineShortcodes = true

# googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "Loïc's Space - Du contenu de qualité sur le marketing, l'entreprenariat et la finance."
  images = ['/favicon.ico']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Accueil'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 2
[[menu.main]]
  name = 'A propos'
  url = '/a-propos'
  weight = 3


[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/loic-monnerat/'
  weight = 1
[[menu.social]]
  name = 'Email'
  url = 'mailto:monneratloic@ikmail.com'
  weight = 2
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/Dakee0'
  weight = 3


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
